version: "3"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: nodered-template
    environment:
      - TZ=Europe/Moscow
    ports:
      - ${DOCKER_APP_PORT}:1880
    volumes:
      - nodereddata:/data

volumes:
  nodereddata:
